/*
 * UART_Config.h
 *
 *  Created on: Sep 22, 2023
 *      Author: moham
 */

#ifndef USART_CONFIG_H_
#define USART_CONFIG_H_

#define USART_MODE					USART_ASYNC
#define USART_BAUDRATE				USART_BAUDRATE_9600
#define USART_PARITY				DISABLE
#define USART_STOP_BITS				USART_STOP_1_BIT
#define USART_DATA_SIZE				USART_DATA_8_BITS
#define USART_CLK_POLARITY			USART_RISING_CLK_EDGE
#define USART_TX_INTERRUPT			DISABLE
#define USART_RX_INTERRUPT			DISABLE
#define USART_REG_EMPTY_INTERRUPT 	DISABLE
#define USART_RECEIVER				ENABLE
#define USART_TRANSMITER			ENABLE


#endif /* USART_CONFIG_H_ */
