/*
 * TIMER0_Config.h
 *
 *  Created on: Sep 16, 2023
 *      Author: moham
 */

#ifndef TIMER0_CONFIG_H_
#define TIMER0_CONFIG_H_


#define TIMER0_MODE					TIMER0_FASTPWM
#define TIMER0_PRESCALER			TIMER0_PRESCALER_64
#define TIMER0_FASTPWM_MODE			TIMER0_PWM_NON_INVERTED
#define TIMER0_PHASECORRECT_MODE	TIMER0_PWM_NON_INVERTED
#define TIMER0_PRELOAD_VALUE		152
#define TIMER0_CTC_VALUE			125
#define TIMER0_COUNTER_VALUE		2442






#endif /* TIMER0_CONFIG_H_ */
